#  _    _       _       _____           _
# | |  | |     | |     |  __ \         | |
# | |__| |_   _| |__   | |__) |_ _ _ __| | _____  _   _ _ __
# |  __  | | | | '_ \  |  ___/ _` | '__| |/ / _ \| | | | '__|
# | |  | | |_| | |_) | | |  | (_| | |  |   < (_) | |_| | |
# |_|  |_|\__,_|_.__/  |_|   \__,_|_|  |_|\_\___/ \__,_|_|
#
# This is the default configuration file for the "HubParkour" by Block2Block.
#
# Do not remove any of the different values. They cannot be disabled, however
# I may introduce a system for them to be disabled in the near future if there
# is enough demand. If you do remove values, the plugin will just load them in
# again with their default values. The same occurs when there is an invalid value
# used.
#
# I have worked quite hard on the plugin to make it as configurable as possible. Please
# rate it on the Spigot page! Every review helps!
#
# If you have any questions, bug reports or suggestions, feel free to add it as an
# issue on the GitHub.
#
# Most of the settings/messages are self explanatory, but I have explained the less obvious ones.

Messages:
    #This is the message that appears when someone joins the server. It can be toggled off in the settings.
    Join-Message: "&2Parkour>> &7This server uses HubParkour by Block2Block."

    #All Hologram messages. Requires HolographicDisplays to be installed.
    Holograms:
        Start: "&9&lParkour Start"
        End: "&9&lParkour End"
        Checkpoint: "&9&lCheckpoint #{checkpoint}"

    #Command related messages. Default values are recommended, but they can all be changed. Server must be restarted for changes to apply.
    Commands:
        #The message that is displayed when a player includes no arguments with the /parkour command.
        No-Arguments: "&2Parkour>> &7Parkour Help:\n&a/parkour reset &7- Sends you back to the start.\n&a/parkour checkpoint &7- Teleports you to the last checkpoint you reached.\n&a/parkour leave &7- Makes you leave the parkour."

        #The message that is displayed when a player types in a sub-command that doesn't exist.
        Unknown-Subcommand: "&2Parkour>> &7That sub-command is unknown!"

        #When a player does not have permission to execute a certain sub-command (only applicable to the admin commands).
        No-Permission: "&2Parkour>> &7You do not have permission to execute this command."

        #The /parkour reset related messages.
        Reset:
            Successful: "&2Parkour>> &7You have been teleported to the start."
            Not-Started-Parkour: "&2Parkour>> &7You must start the parkour in order to reset!"

        #The /parkour reset related messages.
        Checkpoint:
            Successful: "&2Parkour>> &7You have been teleported to your last checkpoint."
            Not-Started-Parkour: "&2Parkour>> &7You must start the parkour in order to teleport to a checkpoint!"

        #The message format for when a player looks at the top 3 leaderboard.
        Top3: "&2Parkour>> &7The top 3 times are:\n&a#1 &7- &a{player1-name} &7- &a{player1-time} &7seconds.\n&a#2 &7- &a{player2-name} &7- &a{player2-time} &7seconds.\n&a#3 &7- &a{player3-name} &7- &a{player3-time} &7seconds."

        #Messages sent when the user uses /parkour leave.
        Leave:
            Left: "&2Parkour>> &7You have left the parkour and your time has been reset."
            Not-In-Parkour: "&2Parkour>> &7You must have started the parkour in order to leave it."

        #Admin command messages.
        Admin:
            Reload:
                Successful: "&2Parkour>> &7Reload successful! If you have changed database or hologram settings, you will need to restart the server in order for those changes to apply."
                Failed: "&2Parkour>> &7The reload failed. Please make sure that you have formatted the file correctly."
            SetStart:
                Successful: "&2Parkour>> &7You have successfully set the startpoint."
                Invalid-Location: "&2Parkour>> &7That location is not valid! Please stand over your specified pressure plate to set the spawn. Check your config.yml to see what this is."
            SetEnd:
                Successful: "&2Parkour>> &7You have successfully set the endpoint."
                Invalid-Location: "&2Parkour>> &7That location is not valid! Please stand over your specified pressure plate to set the send. Check your config.yml to see what this is."
            SetRestart:
                Successful: "&2Parkour>> &7You have successfully set the restart point."
            SetCheck:
                Successful: "&2Parkour>> &7You have successfully set checkpoint #{checkpoint}."
                Invalid-Location: "&2Parkour>> &7That location is not valid! Please stand over your specified pressure plate to set a checkpoint. Check your config.yml to see what this is."
                Number-Format-Error: "&2Parkour>> &7Sorry, that is not a valid checkpoint!"
                Invalid-Arguments: "&2Parkour>> &7Invalid Arguments. Correct Usage: &a/parkour setcheck {checkpoint}"

    #Messages displayed while the user is doing parkour.
    Parkour:
        Started: "&2Parkour>> &7You have started the parkour!"
        Restarted: "&2Parkour>> &7You have restarted the parkour! Your time has been reset to 0!"
        Checkpoints:
            Reached: "&2Parkour>> &7You have reached checkpoint #{checkpoint}! You have received $100 as a reward!"
            Not-Started: "&2Parkour>> &7You must start the parkour in order to reach checkpoints!"
        End:
            Beat-Previous-Personal-Best: "&2Parkour>> &7You beat your previous record and you managed to complete the parkour in {time} seconds! You have received $100 for finishing the parkour!"
            Not-Beat-Previous-Personal-Best: "&2Parkour>> &7You didn't beat your previous record, but you managed to complete the parkour in {time} seconds! You have received $100 for finishing the parkour!"
            First-Time: "&2Parkour>> &7Well done! You completed the parkour in {time} seconds! You received $1000 as a reward for completing the parkour for the first time!"
            Not-Started: "&2Parkour>> &7You must start the parkour in order to finish it."
            Failed:
                Fly: "&2Parkour>> &7You are not allowed to fly while doing the parkour. Parkour failed!"
                Not-Enough-Checkpoints: "&2Parkour>> &7You did not reach enough checkpoints, parkour failed!"

        #Messages displayed when a user finishes the parkour. Basically tells them if they are still on/move onto the leaderboard or not.
        Leaderboard:
            Still-First: "&2Parkour>> &7You are still in 1st place!"
            Now-First: "&2Parkour>> &7Well done! You have entered 1st place!"
            Still-Second: "&2Parkour>> &7You are still in 2nd place!"
            Now-Second: "&2Parkour>> &7Well done! You have entered 2nd place!"
            Still-Third: "&2Parkour>> &7You are still in 3rd place!"
            Now-Third: "&2Parkour>> &7Well done! You have entered 3rd place!"
Settings:
    Holograms: false
    Must-Complete-All-Checkpoints: true
    Join-Message: true
    Version-Checker: true

    #MySQL/SQLite settings. Adds support for cross server player times and leaderboards.
    #Note: The pressure plates must be in exactly the same location (including the types) in all servers in order for this to work.
    Database:
        #If MySQL/SQLite is enabled, the plugin will no longer use file storage except for this config.
        Enabled: false
        Type: "SQLite"

        #Details of the MySQL Database.
        Details:
            MySQL:
                Hostname: "localhost"
                Port: "3306"
                Database: "HubParkour"
                Username: "root"
                Password: ""
            SQLite:
                #The file name MUST end in .db.
                File-Name: "hp-storage.db"

    #Specifies the type of pressure plates that the plugin uses. Values CANNOT be the same. The plugin will disable itself
    #if an invalid or duplicate value is detected. Modify with caution.
    #Valid values: Gold, Iron, Wood, Stone.
    Pressure-Plates:
        Start: "Wood"
        Checkpoint: "Gold"
        End: "Iron"

    #Rewards commands, placeholders: {player-name} for the player's name, {player-uuid} for the player's UUID.
    Rewards:
        Checkpoint-Reward:
            Enabled: true
            Command: "money give {player-name} 100"
        Finish-Reward:
            Enabled: true
            First-Time-Only: false
            First-Time-Command: "money give {player-name} 1000"
            After-Completed-Command: "money give {player-name} 100"