name: HubParkour
main: io.github.Block2Block.HubParkour.Main
version: 1.1.2
author: Block2Block
website: http://forums.raptorpvp.net/
softdepend: [HolographicDisplays]
commands:
   parkour:
      aliases: [pk]
      description: The plugins main commands.
permissions:
   hubparkour.admin:
      default: op
      description: Allows access to the admin commands of HubParkour.